routes/web.php
<?php

Route::resource('/books', 'BookController');

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    protected $fillable = ['name', ];

    public function books(){
        return $this->belongsToMany('App\Book');
    }
}

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable = ['title', 'description'];

    public function authors(){
        return $this->belongsToMany('App\Author');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function show(Author $author)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function edit(Author $author)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Author $author)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Author  $author
     * @return \Illuminate\Http\Response
     */
    public function destroy(Author $author)
    {
        //
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::all();
        return view('book.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('book.create_or_edit', ['edited' => 0]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|min:2|max:255',
        ]);

        $book = Book::create($request->all());
        return redirect('books/' . $book->id)
            ->with('success', trans('message.created'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::findOrFail($id);
        return view('book.show', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edited = 1;
        $book = Book::findOrFail($id);
        return view('book.create_or_edit', compact('book', 'edited'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        Book::findOrFail($book->id)->update($request->all());
        return redirect('books/' . $book->id)->with('success', trans('message.edited'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Book::findOrFail($id)->delete();
        return redirect()
            ->route('books.index')
            ->with('success', trans('message.deleted'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/book/create_or_edit.blade.php
@extends('layouts.default')

@section('content')

<div class="card">
    <div class="card-header">
        <header class="header">
            <p class="card-header-title">
                @if ($edited)
                    @section('title', 'Editar ' . $book->title)
                    Editar {{ $book->title }}
                @else
                    @section('title', 'Agregar nuevo libro')
                    Nuevo Libro
                @endif
            </p>
        </header>
    </div>
    <div class="card-content">
        <form
        @if ($edited)
            action="{{ route('books.update', $book->id) }}"
            @else
        action="{{ route('books.store') }}"
        @endif
            method="post" class="form">
            @csrf
            @if ($edited)
                @method('PATCH')
            @endif
            <div class="field">
                <div class="control">
                    <input type="text" name="title" value="{{ $book->title ?? ''}}" class="input">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input value="{{ $book->description ?? '' }}" class="textarea" name="description">
                </div>
            </div>
            <div class="level">
                <div class="level-left">
                    <a href="#" class="button">Cancelar</a>
                </div>
                <div class="level-right">
                    <button class="button">Guardar</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/book/index.blade.php
@extends('layouts.default')

@section('title', 'Todos los libros')

@section('content')
<h1 class="is-1">Books</h1>
<table class="table">
    <thead>
        <tr>
            <th>Título</th>
            <th>Autores</th>
            <th>Detalle</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($books as $book)
        <tr>
            <td>{{ $book->title }}</td>
            <td>
                @foreach ($book->authors as $author)
                {{ $author->name }},
                @endforeach
            </td>
            <td>
                <a href="{{ route('books.show', $book->id) }}" class="link">ver</a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endsection

resources/views/book/show.blade.php
@extends('layouts.default')

@section('title', 'Libro ' . $book->title)

@section('content')

<div class="card">
    <header class="card-header">
        <p class="card-header-title">
            Libro {{ $book->title }}
        </p>
    </header>
    <div class="card-content">
        <div class="content">
                @if (empty($book->description))
                    No hay descripción
                @else
                    {{ $book->description }}
                @endif
        </div>
        <div class="level">
            <div class="level-left">
               <form action="{{ route('books.destroy', $book->id) }}" class="form" method="post">
                @method('DELETE')
                @csrf
                   <div class="field">
                       <div class="control">
                           <button class="button is-danger">Borrar</button>
                        </div>
                   </div>
               </form>
            </div>
            <div class="level-right">
                <a href="{{ route('books.edit', $book->id) }}" class="button is-info">Editar</a>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/includes/message.blade.php
@if ($message = Session::get('success'))
<div class="notification is-success">
    <button class="delete"></button>
    {{ $message }}
</div>
@endif

@if ($message = Session::get('error'))
<div class="notification is-danger">
    <button class="delete"></button>
    {{ $message }}
</div>
@endif


@if ($message = Session::get('warning'))
<div class="notification is-warning">
    <button class="delete"></button>
    {{ $message }}
</div>
@endif


@if ($message = Session::get('info'))
<div class="notification is-info">
    <button class="delete"></button>
    {{ $message }}
</div>
@endif

@if ($errors->any())
<article class="message is-danger">
    <div class="message-header">
        <p>@lang('message.data_error')</p>
        <button class="delete" aria-label="delete"></button>
    </div>
    <div class="message-body">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
</article>
@endif

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>@yield('title', 'Library')</title>
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    </head>
    <body>
        @include('includes.message')
        @yield('content')
        <script src="{{ asset('js/app.js') }}"></script>
    </body>
</html>